[build]
  # This is a Node.js application, not a static site
  # Railway will handle the build process
  publish = "public"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
